language: node_js
sudo: required
install:
- npm install
after_success: npm run coveralls
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: npm run convert
      deploy:
        provider: npm
        skip_cleanup: true
        all_branches: true
        api_key: $NPM_TOKEN
env:
  global:
    secure: D02YgDzW5Ig6WWYXK7wL1qzmsUHeE3rRv3JK7IIZ2S1IuYJaKBfyRUag08lhrOLOsm4G/4QB+i0A6/X3EyGvdKuZea7tXbPMbsG7DwTzzdEfGX1bZwrtyXGrXPQY5Z0ggJCxjDxk7GkgnTgHPHqaCLPVurccwiXE/Yj0vvNNxn0=
